/* ---------- SNAPSHOT CHANGE ---------- */
function goSnap(idx,anim){cur=idx;paintNodes(anim);paintHeader();clock();renderPane();paintInspector(sel);var sw=document.getElementById("sweep");if(anim){sw.classList.remove("go");void sw.offsetWidth;sw.classList.add("go");}T(function(){sw.classList.remove("go");},450);}
(function ticks(){var t=document.getElementById("ticks"),h="";for(var i=0;i<SNAPS.length;i++){var pct=SNAPS.length===1?0:(i/(SNAPS.length-1))*100;h+='<div class="tk" data-i="'+i+'" style="left:'+pct+'%"></div>';}t.innerHTML=h;for(var i=0;i<t.children.length;i++)t.children[i].addEventListener("click",function(){goSnap(parseInt(this.getAttribute("data-i")),true);});}());
document.getElementById("rp").addEventListener("click",function(){if(replaying)return;replaying=true;var btn=this;btn.textContent="REWINDING…";banner("TEMPORAL REWIND · 2026-05-04");goSnap(0,true);T(function(){for(var i=1;i<SNAPS.length;i++){T(function(idx){return function(){goSnap(idx,true);};}(i),i*280);}T(function(){replaying=false;btn.textContent="REPLAY ▶";},SNAPS.length*280+500);}(),500);});
function banner(txt){var b=document.getElementById("phb");b.textContent=txt;b.classList.remove("on");void b.offsetWidth;b.classList.add("on");T(function(){b.classList.remove("on");},1500);}
document.getElementById("sig").addEventListener("click",function(){clearSeq();resetChain(false);var t=0;banner("INITIALIZING VALKYRIE");T(function(){banner("MACRO SHOCK DETECTED");switchTab("MACRO");select("macro_cpi",{sweep:true});},350);});
document.getElementById("rst").addEventListener("click",function(){clearSeq();resetChain(false);goSnap(SNAPS.length-1,true);select("sig_rates",{sweep:false});});
(function hover(){var gs=document.querySelectorAll(".nrow");for(var i=0;i<gs.length;i++){gs[i].addEventListener("mouseenter",function(){var id=this.getAttribute("data-id"),n=NM[id],w=n.T?TW:NW,h=n.T?TH:NH;});gs[i].addEventListener("mouseleave",function(){});gs[i].addEventListener("click",function(){select(this.getAttribute("data-id"));});};}());
var tabsEl=document.querySelectorAll(".tab");for(var i=0;i<tabsEl.length;i++)tabsEl[i].addEventListener("click",function(){switchTab(this.getAttribute("data-t"));});
/* MACRO STREAMLIT BUTTON */
document.getElementById("macroBtn").addEventListener("click",function(){window.location.href="http://localhost:8501";});
var chips=document.querySelectorAll(".chip");for(var i=0;i<chips.length;i++)chips[i].addEventListener("click",function(){if(replaying)return;var q=this.getAttribute("data-q"),nid=this.getAttribute("data-n")||"sig_rates";clearSeq();resetChain(false);select(nid,{sweep:true});});
document.getElementById("ci").addEventListener("keydown",function(e){if(e.key!=="Enter")return;var v=this.value,nid=/채권|듀레이션|커브|금리 포지션/.test(v)?"sig_rates":(/IPO|청약|신주|시장/.test(v)?"sig_equity":"macro_cpi");clearSeq();resetChain(false);select(nid,{sweep:true});this.value="";});
function post(){try{parent.postMessage({type:"wrks:viz:resize",height:document.documentElement.scrollHeight},"*");}catch(err){}}
window.addEventListener("resize",function(){initField();post();});document.addEventListener("visibilitychange",function(){if(!document.hidden&&!fieldRAF)fieldRAF=requestAnimationFrame(field);});
document.getElementById("cw").addEventListener("mousemove",function(e){if(e.target.closest&&e.target.closest(".nrow"))return;var r=this.getBoundingClientRect(),x=Math.round(e.clientX-r.left),y=Math.round(e.clientY-r.top);});
(function boot(){initField();field();paintNodes(false);paintHeader();clock();renderPane();document.getElementById("n_sig_rates").classList.add("sel");var ids=["bt1","bt2","bl0","bl1","bl2","bl3"];var idx=0;function showNext(){if(idx>=ids.length){document.getElementById("boot").classList.add("off");T(function(){document.getElementById("boot").style.display="none";},450);return;}var el=document.getElementById(ids[idx]);if(el)el.style.opacity="1";idx++;T(showNext,200);}showNext();}());
